public class mapDraw {
	public mapDraw() 
    {
    	//draw the map in ASCII characters! :D
    	// use these
    	//  ║  ═  ╔  ╗  ╚  ╝  ╠  ╣  ╦  ╩  ╬		(indoors rooms)
		//  │  ─  └  ┘  ┌  ┐  ├  ┤  ┬  ┴  ┼		(outdoor rooms)
    	//  ←  →  ↑  ↓
		
		if (Game.curRoomPlayer == 1)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                     X                        │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 2)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL  X  ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 3)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                X     │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 4)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║ X ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 5)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║     X                │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 6)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║       X       ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 7)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM  X║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 8)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║X ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 9)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║   X   ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 10)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║X ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 11)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║X Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 12)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║   X    A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 13)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓ X  │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 14)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │             X            │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 15)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM  X║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 16)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓ X                     │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 17)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║       X       ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 18)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║    X     ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 19)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║X  STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗                    │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		if (Game.curRoomPlayer == 20)
		{
			System.out.println("          ╔══════════════════════════════════════════╗ ┌──────────────────────────────────────────────┐");
	    	System.out.println("          ║        A         W  I  N  G              ║ │                                              │");
	    	System.out.println("          ╚══════════════════════════════════════════╝ │                                              │");
	    	System.out.println("            ↓             ↑                      ↑↓    │                                              │");
	    	System.out.println("          ╔══╗           ╔══╗    ╔══════════╗ ╔══════╗ │                                              │");
	    	System.out.println("          ║3 ║           ║  ║    ║AUDITORIUM║←║A-HALL║←│                                              │");
	    	System.out.println("          ║  ║           ║  ║    ║          ║→╚══════╝→│                  OUTSIDE                     │");
	    	System.out.println("          ║H ║           ║2 ║    ╚══════════╝    ↑↓    │                                              │");
	    	System.out.println("          ║  ║           ║  ║         ↑↓        ╔═══╗  │                                              │");
	    	System.out.println("          ║A ║ ╔═══════╗ ║  ║    ╔══════════╗   ║   ║  │                                              │");
	    	System.out.println("          ║  ║ ║       ║ ║H ║    ║   STAGE  ║   ║ 1 ║  └───────────────────┐                          │");
	    	System.out.println("          ║L ║ ║       ║ ║  ║    ╚══════════╝   ║   ║            ↑↓        │                          │");
	    	System.out.println("          ║  ║ ║  GYM  ║ ║A ║                   ║   ║ ╔══════════════════╗ │                          │");
	    	System.out.println("          ║L ║→║       ║←║  ║ ╔═══════════════╗ ║   ║←║    MAIN HALL     ║ │                          │");
	    	System.out.println("          ║  ║←║       ║→║L ║→║     LUNCH     ║←║ H ║ ╚══════════════════╝ │                          │");
	    	System.out.println("╔═══════╗ ║  ║ ╚═══════╝ ║  ║←║               ║→║   ║               ↑↓     │                          │");
	    	System.out.println("║ Secret║←║  ║           ║L ║ ╚═══════════════╝ ║ A ║            ╔═══════╗ │                          │");
	    	System.out.println("║  Room ║→║  ║           ║  ║         ↑↓        ║   ║ ╔═══════╗  ║ OFFICE║ │                          │");
	    	System.out.println("╚═══════╝ ╚══╝           ╚══╝   ╔══════════╗    ║ L ║←║ 1-20  ║  ║ ROOM  ║ │                          │");
	    	System.out.println("           ↑↓                   ║JANITOR'S ║    ║   ║→╚═══════╝  ╚═══════╝ │                          │");
	    	System.out.println(" ┌──────────────────────────┐   ║   ROOM   ║    ║ L ║                      │                          │");
	    	System.out.println(" │            Y             │   ╚══════════╝    ║   ║                      │                          │");
	    	System.out.println(" │                          │                   ╚═══╝                      │                          │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │         FOOTBALL         │     ╔══════════╗ ╔══════╗        X           │                          │");
	    	System.out.println(" │                          │     ║ PILLET'S ║→║SOUTH ║ ╔════════════════╗ │                          │");
	    	System.out.println(" │                          │     ║   ROOM   ║←║ EXIT ║←║   H - H A L L  ║←│ → go east to land in     │");
	    	System.out.println(" ├────────────┤S├───────────┤     ╚══════════╝ ╚══════╝→╚════════════════╝ │   h-hall                 │");
	    	System.out.println(" │                          │                     ↑↓                       │                          │");
	    	System.out.println(" │                          │               ╔═══════════════╗              │                          │");
	    	System.out.println(" │          FIELD           │               ║               ║              │                          │");
	    	System.out.println(" │                          │       →       ║STUDENT PARKING║              │                          │");
	    	System.out.println(" │                          │       ←       ║               ║              │                          │");
	    	System.out.println(" │             Y            │               ╚═══════════════╝              │                          │");
	    	System.out.println(" └──────────────────────────┘                                              └──────────────────────────┘");
	    	System.out.println("*please note, the map does not actualy represent \"Sunset Highschoool\" just my own version of it!*    ");
		}
		System.out.println("										X = You Are Here Marker");
    }
	public static void main(String[] args) {
		new mapDraw();
	}
}